module.exports = [
    { "id": 1, "name": "Tuna", "location": "Laut", "image": require("./assets/images/tuna.jpg") },
    { "id": 2, "name": "Salmon", "location": "Laut", "image": require("./assets/images/salmon.jpg") },
    { "id": 3, "name": "Sardines", "location": "Laut", "image": require("./assets/images/sardines.jpg") },
    { "id": 4, "name": "Cod", "location": "Laut", "image": require("./assets/images/cod.jpg") },
    { "id": 5, "name": "Mackerel", "location": "Laut", "image": require("./assets/images/mackerel.jpg") },
    { "id": 6, "name": "Rainbow Shark", "location": "Asia", "image": require("./assets/images/rainbow_shark.jpg") },
    { "id": 7, "name": "Discus", "location": "Amazon", "image": require("./assets/images/discus.jpg") },
    { "id": 8, "name": "Betta Fish", "location": "Asia", "image": require("./assets/images/betta_fish.jpg") },
    { "id": 9, "name": "Goldfish", "location": "Asia", "image": require("./assets/images/goldfish.jpg") },
    { "id": 10, "name": "Angelfish", "location": "Amazon", "image": require("./assets/images/angelfish.jpg") },
    { "id": 11, "name": "Guppy", "location": "South America", "image": require("./assets/images/guppy.jpg") },
    { "id": 12, "name": "Koi", "location": "Asia", "image": require("./assets/images/koi.jpg") },
    { "id": 13, "name": "Molly", "location": "Central America", "image": require("./assets/images/molly.jpg") },
    { "id": 14, "name": "Neon Tetra", "location": "South America", "image": require("./assets/images/neon_tetra.jpg") },
    { "id": 15, "name": "Platy", "location": "Central America", "image": require("./assets/images/platy.jpg") },
    { "id": 16, "name": "Swordtail", "location": "Mexico", "image": require("./assets/images/swordtail.jpg") },
    { "id": 17, "name": "Tiger Barb", "location": "Indonesia", "image": require("./assets/images/tiger_barb.jpg") },
    { "id": 18, "name": "Pleco", "location": "South America", "image": require("./assets/images/pleco.jpg") },
    { "id": 19, "name": "Corydoras Catfish", "location": "South America", "image": require("./assets/images/corydoras_catfish.jpg") },
    { "id": 20, "name": "Amano Shrimp", "location": "Japan", "image": require("./assets/images/amano_shrimp.jpg") },
    { "id": 21, "name": "Snail", "location": "Worldwide", "image": require("./assets/images/snail.jpg") },
    { "id": 22, "name": "Red Cherry Shrimp", "location": "Taiwan", "image": require("./assets/images/red_cherry_shrimp.jpg") },
    { "id": 23, "name": "Blue Ram", "location": "South America", "image": require("./assets/images/blue_ram.jpg") },
    { "id": 24, "name": "Electric Yellow Cichlid", "location": "Africa", "image": require("./assets/images/electric_yellow_cichlid.jpg") },
    { "id": 25, "name": "Lampam", "location": "Tawar", "image": require("./assets/images/lampam.jpg") },
    { "id": 26, "name": "Gurame", "location": "Tawar", "image": require("./assets/images/gurame.jpg") },
    { "id": 27, "name": "Pearl Gourami", "location": "Asia Tenggara", "image": require("./assets/images/pearl_gourami.jpg") },
    { "id": 28, "name": "Cupang", "location": "Tawar", "image": require("./assets/images/cupang.jpg") },
    { "id": 29, "name": "Arwana", "location": "Tawar", "image": require("./assets/images/arwana.jpg") },
    { "id": 30, "name": "Botia", "location": "Tawar", "image": require("./assets/images/botia.jpg") },
    { "id": 31, "name": "Koki", "location": "Tawar", "image": require("./assets/images/koki.jpg") },
    { "id": 32, "name": "Clown Fish", "location": "Laut", "image": require("./assets/images/clown_fish.jpg") },
    { "id": 33, "name": "Kakap", "location": "Laut", "image": require("./assets/images/kakap.jpg") },
    { "id": 34, "name": "Teri", "location": "Laut", "image": require("./assets/images/teri.jpg") },
    { "id": 35, "name": "Gabus", "location": "Tawar", "image": require("./assets/images/gabus.jpg") },
    { "id": 36, "name": "Belut", "location": "Tawar", "image": require("./assets/images/belut.jpg") },
    { "id": 37, "name": "Piranha", "location": "Tawar", "image": require("./assets/images/piranha.jpg") },
    { "id": 38, "name": "Betta", "location": "Tawar", "image": require("./assets/images/betta.jpg") },
    { "id": 39, "name": "Kissing Gourami", "location": "Asia Tenggara", "image": require("./assets/images/kissing_gourami.jpg") },
    { "id": 41, "name": "Bristlenose Pleco", "location": "Amazon", "image": require("./assets/images/bristlenose_pleco.jpg") },
    { "id": 42, "name": "Giant Danio", "location": "Asia Tenggara", "image": require("./assets/images/giant_danio.jpg") },
    { "id": 43, "name": "Harlequin Rasbora", "location": "Asia Tenggara", "image": require("./assets/images/harlequin_rasbora.jpg") },
    { "id": 44, "name": "Electric Eel", "location": "Amazon", "image": require("./assets/images/electric_eel.jpg") },
    { "id": 45, "name": "Black Ghost Knifefish", "location": "Amazon", "image": require("./assets/images/black_ghost_knifefish.jpg") }
  ]